import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { startCheckout } from "~/lib/client-api";

export const Route = createFileRoute("/es")({ component: SpanishHome });

function LogoMark() { return <svg viewBox="0 0 40 40" className="h-8 w-8" aria-hidden="true"><rect width="40" height="40" rx="10" fill="#0F172A"/><path d="M12 21l5.5 5.5L28 14" stroke="#F59E0B" strokeWidth="3.5" fill="none" strokeLinecap="round" strokeLinejoin="round"/></svg>; }
function Wordmark() { return <span className="text-lg font-bold tracking-tight text-slate-900">Blamo<span className="text-slate-400"> Closing</span></span>; }
function Arrow() { return <span aria-hidden="true">→</span>; }
function BuyButton({ slug, label }: { slug: string; label: string }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState(false);
  async function buy() { if (busy) return; setBusy(true); setError(false); try { const url = await startCheckout(slug, localStorage.getItem("blamo-promo") || undefined); window.location.href = url; } catch (e) { if (e instanceof Error && e.message === "login_required") { window.location.href = `/login?next=${encodeURIComponent(`/es#${slug}`)}`; return; } setError(true); setBusy(false); } }
  return <div><button type="button" onClick={buy} disabled={busy} className="inline-flex items-center gap-2 rounded-lg bg-amber-500 px-4 py-2.5 text-sm font-bold text-slate-950 shadow-sm transition hover:bg-amber-400 disabled:opacity-60">{busy ? "Procesando…" : label} <Arrow /></button>{error && <p className="mt-2 text-xs text-red-600">El pago no está disponible por el momento.</p>}</div>;
}
function Art({ kind, side }: { kind: string; side: "left" | "right" }) { return <img src={`/bg-${kind}.svg`} alt="" aria-hidden="true" className={`pointer-events-none absolute bottom-0 ${side === "left" ? "-left-8" : "-right-8"} w-36 opacity-20`} />; }
const products = [
  { slug: "starter-kit-es", img: "starter-kit-es.png", title: "El Kit de Inicio del Vendedor", desc: "Los 10 Pasos de la Venta: guiones palabra por palabra, listas de verificación y un plan de práctica de 7 días.", price: "$24.99", chip: "27 páginas · Saludo → Seguimiento" },
  { slug: "spouse-es", img: "spouse-es.png", title: "El Manual de la Objeción del Cónyuge", desc: "10 cierres para “necesito consultarlo con mi esposo(a)” y cómo distinguir una objeción real de una demora.", price: "$6.99", chip: "Diez cierres, cero presión" },
  { slug: "trade-in-es", img: "trade-in-es.png", title: "El Manual del “Quiero Más por Mi Trade-In”", desc: "10 cierres para la objeción del intercambio, incluido el cierre favorito del propietario.", price: "$6.99", chip: "El cierre de intercambio favorito" },
  { slug: "qualifying-questions-es", img: "qualifying-questions-es.png", title: "La Guía de Preguntas de Calificación", desc: "75 preguntas en nueve categorías, el Golden 10 y el flujo de Razón → Necesidad → Presupuesto → Compromiso.", price: "$6.99", chip: "75 preguntas · Golden 10" },
];
function ProductCard({ p }: { p: typeof products[number] }) { return <article id={p.slug} className="relative product-card overflow-visible rounded-2xl bg-white shadow-xl ring-1 ring-slate-900/10"><div className="absolute -right-3 -top-3 z-10 rounded-xl border border-slate-200 bg-white px-3 py-2 text-[10px] font-bold uppercase tracking-wider text-slate-500 shadow-lg">PDF · Español</div><img src={`/cover-thumbs/${p.img}`} alt={`Portada: ${p.title}`} width="600" height="800" loading="lazy" className="aspect-[3/4] w-full rounded-t-2xl object-cover"/><div className="p-5"><h3 className="text-lg font-bold leading-snug text-slate-900">{p.title}</h3><p className="mt-2 text-sm leading-relaxed text-slate-600">{p.desc}</p><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><strong className="text-xl text-slate-900">{p.price}</strong><BuyButton slug={p.slug} label={`Comprar — ${p.price}`} /></div><p className="mt-4 text-xs font-semibold text-slate-500">{p.chip}</p></div></article>; }
function SpanishHome() { return <div className="min-h-dvh bg-white" lang="es">
  <header className="sticky top-0 z-40 border-b border-slate-200/70 bg-white/90 backdrop-blur"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-6"><a href="#top" className="flex items-center gap-2.5"><LogoMark/><Wordmark/></a><nav className="hidden items-center gap-5 lg:flex"><a href="#pasos" className="text-sm font-medium text-slate-500 hover:text-slate-900">Los 10 Pasos de la Venta</a><a href="#catalogo" className="text-sm font-medium text-slate-500 hover:text-slate-900">Catálogo</a><a href="/contact" className="text-sm font-medium text-slate-500 hover:text-slate-900">Contacto</a><a href="/" className="text-sm font-bold text-amber-700 hover:text-amber-500">English</a><a href="#paquete" className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white hover:bg-slate-700">Obtén el Paquete Completo — $79.99</a></nav></div></header>
  <section id="top" className="hero-brand relative overflow-hidden bg-slate-50"><Art kind="car" side="left"/><Art kind="mascot" side="right"/><div className="relative mx-auto grid max-w-6xl items-center gap-10 px-6 pb-20 pt-16 lg:grid-cols-[1.05fr_.95fr] lg:py-28"><div className="max-w-2xl text-center sm:text-left"><div className="mb-6 flex items-center justify-center gap-3 sm:justify-start"><LogoMark/><div><p className="text-xl font-extrabold text-slate-950">Blamo<span className="text-amber-500"> Closing</span></p><p className="text-[10px] font-bold uppercase tracking-[.2em] text-slate-500">Entrenamiento de ventas</p></div></div><p className="text-sm font-bold uppercase tracking-[.16em] text-amber-700">Entrenamiento real de concesionarios. Cierres más claros.</p><p className="mt-3 text-base font-extrabold text-slate-900">★ Más de 20 años de experiencia en concesionarios — un proceso comprobado que funciona.</p><h1 className="mt-4 text-4xl font-extrabold leading-tight tracking-tight text-slate-950 sm:text-6xl">Cierra con más claridad, desde hoy</h1><p className="mt-6 text-lg font-extrabold leading-snug text-slate-900">¿Cansado de que te lancen a los lobos? ¿Sin entrenamiento real en el trabajo? Déjanos ayudarte.</p><p className="mt-3 text-base leading-relaxed text-slate-600 sm:text-lg">Blamo Closing ofrece entrenamiento práctico para vendedores de concesionarios: guiones de cierre, manuales de objeciones y guías PDF basadas en conversaciones reales de ventas.</p><div className="mt-7 grid gap-3 text-left sm:grid-cols-3"><span className="text-sm font-semibold">✓ Guiones palabra por palabra</span><span className="text-sm font-semibold">✓ Respuestas para objeciones difíciles</span><span className="text-sm font-semibold">✓ Material práctico para usar hoy</span></div><div className="mt-9 flex flex-wrap justify-center gap-5 sm:justify-start"><a href="#catalogo" className="rounded-xl bg-amber-500 px-7 py-4 font-bold text-slate-950 shadow-lg hover:bg-amber-400">Ver el entrenamiento <Arrow/></a><a href="#beneficios" className="py-4 text-sm font-bold text-slate-700 underline decoration-amber-400 decoration-2 underline-offset-4">Cómo funciona ↓</a></div></div><div className="relative mx-auto flex min-h-[300px] w-full max-w-md items-end justify-center"><img src="/blamo-mascot.svg" alt="Mascota de Blamo Closing" className="mascot-float w-64 drop-shadow-2xl sm:w-80"/></div></div></section>
  <section id="beneficios" className="relative overflow-hidden border-t border-slate-100"><Art kind="happy-rep" side="right"/><div className="mx-auto max-w-6xl px-6 py-20"><p className="text-xs font-semibold uppercase tracking-[.18em] text-amber-700">Lo que hace por usted</p><h2 className="mt-3 text-3xl font-bold text-slate-900 sm:text-4xl">Un proceso completo, no una colección de trucos</h2><p className="mt-4 max-w-2xl text-lg leading-relaxed text-slate-600">El Kit de Inicio guía a cada cliente por los mismos diez pasos en orden, para que nunca se salte un paso ni tenga que adivinar qué sigue.</p><ul className="mt-10 grid gap-6 md:grid-cols-2">{["Guíe a cada cliente por el proceso completo, sin saltarse pasos.","Sepa qué decir en cada momento: saludo, descubrimiento de necesidades, presentación, prueba de manejo y papeleo.","Responda a objeciones de precio, financiamiento y características con honestidad y sin presión.","Negocie un verdadero beneficio para ambas partes, intercambiando valor por valor.","Convierta una venta en muchas con seguimiento, reseñas, referidos y clientes recurrentes.","Úselo hoy mismo: listas de verificación, referencia rápida y plan de práctica de 7 días."].map(x=><li key={x} className="flex gap-3 text-[1.05rem] leading-relaxed text-slate-700"><b className="text-amber-600">✓</b>{x}</li>)}</ul></div></section>
  <section id="inside" className="relative overflow-hidden bg-slate-50"><Art kind="handshake" side="left"/><div className="mx-auto max-w-6xl px-6 py-20"><p className="text-xs font-semibold uppercase tracking-[.18em] text-amber-700">Lo que incluye</p><h2 className="mt-3 text-3xl font-bold text-slate-900 sm:text-4xl">Cada paso, cada guion, cada lista</h2><div id="pasos" className="mt-10 grid gap-4 sm:grid-cols-2">{["Los 10 pasos en orden: Saludo, Comprender necesidades, Presentar beneficios, Prueba de manejo, Revisar comentarios, Resolver objeciones, Negociar, Papeleo, Entrega y Seguimiento.","El objetivo de cada paso, las palabras del propietario y el error común que debe evitar.","Guiones palabra por palabra para cada etapa, desde el primer saludo hasta la llamada de seguimiento.","Marco de planificación para negociar: conozca su rango y encuentre el beneficio mutuo.","Lista de verificación para cada paso, plan de práctica de la primera semana y referencia rápida."].map(x=><div key={x} className="rounded-xl border border-slate-200 bg-white p-5 text-[.95rem] leading-relaxed text-slate-700 shadow-sm">✓ {x}</div>)}</div></div></section>
  <section id="audiencia" className="relative overflow-hidden"><div className="mx-auto max-w-6xl px-6 py-20"><p className="text-xs font-semibold uppercase tracking-[.18em] text-amber-700">Para quién es</p><h2 className="mt-3 text-3xl font-bold text-slate-900 sm:text-4xl">Entrenamiento para toda la operación</h2><div className="mt-10 grid gap-6 md:grid-cols-3">{[["Nuevos vendedores","Para quien necesita un proceso claro, guiones útiles y confianza desde el primer día."],["Profesionales de ventas","Para quien quiere mejorar sus cierres, manejar objeciones y producir resultados constantes."],["Gerentes y líderes","Para quien desea capacitar, entrenar y elevar el estándar de su equipo."]].map(([h,p])=><div key={h} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="text-lg font-bold text-slate-900">{h}</h3><p className="mt-2 leading-relaxed text-slate-600">{p}</p></div>)}</div></div></section>
  <section id="catalogo" className="bg-slate-900 px-6 py-20 text-white"><div className="mx-auto max-w-6xl"><p className="text-xs font-semibold uppercase tracking-[.18em] text-amber-400">La oferta principal</p><h2 className="mt-3 text-3xl font-bold sm:text-4xl">Elija el acceso completo</h2><div id="paquete" className="mt-10 grid items-center gap-8 rounded-3xl bg-gradient-to-br from-amber-300 to-amber-500 p-7 text-slate-950 shadow-2xl sm:p-10 lg:grid-cols-[1fr_auto]"><div><p className="text-xs font-black uppercase tracking-widest">★ Mejor valor · Inglés + Español</p><h3 className="mt-3 text-2xl font-extrabold sm:text-3xl">Paquete Completo: Todo lo que necesita para tener éxito en ventas automotrices</h3><p className="mt-3 max-w-2xl text-lg font-semibold">Los 24 títulos actuales (inglés + español) y todos los títulos futuros — un solo desbloqueo para toda la biblioteca.</p><p className="mt-4 font-bold"><s>$239.76</s> <span className="ml-2 rounded-full bg-slate-950 px-3 py-1 text-amber-300">Ahorre 67%</span></p><p className="mt-2 text-4xl font-black">$79.99</p><p className="mt-2 text-sm font-bold">Con BLAMO10: $71.99</p></div><BuyButton slug="complete-package" label="Obtén el paquete — $79.99"/></div><h2 className="mt-20 text-center text-3xl font-bold"><span className="text-amber-400">En Español</span></h2><p className="mx-auto mt-3 max-w-2xl text-center text-slate-300">Guías de lectura práctica para vender con más claridad.</p><div className="mt-12 grid gap-10 sm:grid-cols-2 lg:grid-cols-4">{products.map(p=><ProductCard key={p.slug} p={p}/>)}</div><p className="mt-12 text-center text-sm text-slate-300"></p></div></section>
  <section className="bg-amber-500 px-6 py-16 text-center text-slate-950"><h2 className="text-3xl font-extrabold">Empiece a cerrar con más claridad</h2><p className="mx-auto mt-3 max-w-xl text-lg">El Kit de Inicio le da un proceso que puede usar en el piso de ventas hoy.</p><a href="#starter-kit-es" className="mt-7 inline-block rounded-xl bg-slate-950 px-7 py-4 font-bold text-white hover:bg-slate-800">Ver el Kit de Inicio <Arrow/></a></section>
  <section id="faq" className="mx-auto max-w-4xl px-6 py-20"><p className="text-xs font-semibold uppercase tracking-[.18em] text-amber-700">Preguntas frecuentes</p><div className="mt-8 grid gap-6">{[["¿Cómo recibo mi guía?","Después del pago, el código se desbloquea en su cuenta y aparece en la página de confirmación y en Sus compras."],["¿Recibiré un correo con el código?","Stripe envía el recibo de pago por correo. El código se entrega de forma segura dentro de su cuenta."],["¿El Paquete Completo incluye español?","Sí. Incluye los 24 títulos actuales en inglés y español, además de todos los títulos futuros." ]].map(([q,a])=><div key={q} className="border-b border-slate-200 pb-5"><h3 className="font-bold text-slate-900">{q}</h3><p className="mt-2 leading-relaxed text-slate-600">{a}</p></div>)}</div></section>
  <footer className="border-t border-slate-200 px-6 py-8 text-center text-sm text-slate-500"><a href="/" className="font-semibold text-slate-700 hover:text-slate-950">Volver a la página en English</a> · <a href="/contact" className="font-semibold text-slate-700">Contacto</a></footer>
</div>; }
