import { currentUser } from "../../lib/accounts";
import { sql } from "../../db";
import { findCatalogProduct } from "../../lib/catalog";
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json"}});
const OWNER="blnctm@gmail.com";
function key(r:Request){const k=process.env.ADMIN_KEY,g=r.headers.get("x-admin-key")??"";return !!k&&g===k}
async function auth(r:Request){if(key(r))return true;const u=await currentUser(r);return u?.email.toLowerCase()===OWNER}
async function body(r:Request){try{const x=await r.json();return x&&typeof x==="object"?x as Record<string,unknown>:null}catch{return null}}
function mapped(r:any){return{id:String(r.id),text:String(r.text),status:String(r.status),createdAt:new Date(String(r.created_at)).toISOString(),userEmail:String(r.user_email??""),userName:String(r.user_name??""),productSlug:r.product_slug?String(r.product_slug):null,productName:r.product_slug?(findCatalogProduct(String(r.product_slug))?.name??String(r.product_slug)):null}}
export async function handleTestimonial(r:Request){if(r.method!=="POST")return json({error:"method_not_allowed"},405);const u=await currentUser(r);if(!u)return json({error:"unauthorized"},401);const b=await body(r),text=typeof b?.text==="string"?b.text.trim():"";if(text.length<20)return json({error:"too_short",message:"Tell us a little more — at least 20 characters."},400);if(text.length>600)return json({error:"too_long",message:"Reviews must be 600 characters or fewer."},400);const p=await sql()`select id from purchases where user_id=${u.id} and status in ('unlocked','paid') order by created_at desc limit 1`;if(!p[0])return json({error:"not_verified",message:"Only verified buyers can leave a review."},403);const e=await sql()`select id,status from testimonials where user_id=${u.id} order by submitted_at desc limit 1`;if(e[0]&&String((e[0] as any).status)!=="rejected")return json({error:"already_submitted",status:String((e[0] as any).status)},409);const pid=String((p[0] as any).id);const rows=e[0]?await sql()`update testimonials set text=${text},purchase_id=${pid},status='pending',submitted_at=now(),created_at=now(),resolved_at=null where id=${String((e[0] as any).id)} returning id,text,status,created_at`:await sql()`insert into testimonials(user_id,purchase_id,text) values(${u.id},${pid},${text}) returning id,text,status,created_at`;return json({ok:true,testimonial:mapped(rows[0])})}
export async function handleTestimonialsPublic(r:Request){if(r.method!=="GET")return json({error:"method_not_allowed"},405);const rows=await sql()`select t.text,t.created_at,p.product_slug from testimonials t left join purchases p on p.id=t.purchase_id where t.status='approved' order by t.created_at desc`;return json({ok:true,testimonials:(rows as any[]).map(x=>({text:String(x.text),createdAt:new Date(String(x.created_at)).toISOString(),productName:x.product_slug?(findCatalogProduct(String(x.product_slug))?.name??String(x.product_slug)):undefined}))})}
export async function handleTestimonialsPending(r:Request){if(r.method!=="GET")return json({error:"method_not_allowed"},405);if(!(await auth(r)))return json({error:"unauthorized"},401);const rows=await sql()`select t.id,t.text,t.status,t.created_at,u.email user_email,u.name user_name,p.product_slug from testimonials t join users u on u.id=t.user_id left join purchases p on p.id=t.purchase_id where t.status='pending' order by t.created_at asc`;return json({ok:true,testimonials:(rows as any[]).map(mapped)})}
async function resolve(r:Request,status:string){if(r.method!=="POST")return json({error:"method_not_allowed"},405);if(!(await auth(r)))return json({error:"unauthorized"},401);const b=await body(r),id=typeof b?.id==="string"?b.id:"";if(!id)return json({error:"invalid_request"},400);const f=await sql()`select id,status from testimonials where id=${id}`;if(!f[0])return json({error:"not_found"},404);if(String((f[0] as any).status)!=="pending")return json({error:"not_pending"},400);const x=await sql()`update testimonials set status=${status},resolved_at=now() where id=${id} returning id,status`;return json({ok:true,testimonial:x[0]})}
export const handleTestimonialApprove=(r:Request)=>resolve(r,"approved");export const handleTestimonialReject=(r:Request)=>resolve(r,"rejected");
